from pathlib import Path

##############################
# Globals
##############################

PROJECT_DIR = Path(".").absolute()
PROJECT_NAME = "{{ cookiecutter.repo_name }}"

workdir: PROJECT_DIR

configfile: Path("config/config.yml")

##############################
# Includes
##############################

#include: src/snakemake/step_1.smk
#include: src/snakemake/step_2.smk

##############################
# Project rules
##############################
RESULT_FILES = []

rule all:
    """Default rule to generate final report/results"""
    input: RESULT_FILES
    shell:
        "echo Modify all rule to generate relevant target and list relevant result files"

